name: sonar-scanner

on:
#   pull_request:
#     branches: 
#       - develop  
  push: 
    branches: 
      - master
  pull_request:
    branches: 
      - master
    


jobs:
  
  test:
    runs-on: ubuntu-latest  
    steps:
    
    - name: checkout
      uses: actions/checkout@v1
    - name: "Check if user has write access"
      uses: "lannonbr/repo-permission-check-action@2.0.0"
      with:
        permission: "write"
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run sonarqube on push
      if: success() &&  github.secrets.SONAR_TOKEN > 0 
      env: 
        PROJECT_KEY: VA
        HOST_URL: https://sonar.openbsl.ru
      run: echo ddd ${{ secrets.SONAR_TOKEN }}
    
